version = 1

test_patterns = [
  "test/*"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["pyproject.toml", ]
enabled = true
dependency_file_paths = ["pyproject.toml", ]

  [analyzers.meta]
  runtime_version = "3.x.x"
  
[[analyzers]]
name = "test-coverage"
enabled = true
