name: build-and-publish

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox build env
        run: tox -r -e build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/

  publish:
    name: publish-to-pypi
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/project/ScraperFC/
    steps: 
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          skip-existing: true
