name: test

on: push

jobs:
  test-capology:
    name: test-capology
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-capology -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_capology.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-clubelo:
    name: test-clubelo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-clubelo -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_clubelo.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-fbref:
    name: test-fbref
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-fbref -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_fbref.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-sofascore:
    name: test-sofascore
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-sofascore -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_sofascore.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-transfermarkt:
    name: test-transfermarkt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-transfermarkt -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_transfermarkt.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-understat:
    name: test-understat
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox and uv
        run: pip install tox uv
      - name: Run tox test env
        run: tox -r -e test-understat -- --basepython ${{ matrix.python.toxenv }}
      - name: Send coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        if: always()
        with:
          key: python
          coverage-file: coverage_understat.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
  test-build-docs:
    name: test-build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Rox tox env to build docs
        run: tox -r -e docs
